# Generated by Django 4.2.19 on 2025-03-12 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=50)),
                ("qty", models.IntegerField()),
                ("price", models.FloatField()),
                ("discount", models.FloatField()),
                ("total", models.FloatField(editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerAdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=100)),
                ("customer_phone", models.CharField(max_length=15)),
                ("customer_address_1", models.CharField(max_length=100)),
                (
                    "customer_address_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("customer_town", models.CharField(max_length=100)),
                ("customer_postcode", models.CharField(max_length=20)),
                ("customer_county", models.CharField(max_length=100)),
                ("customer_name_ship", models.CharField(max_length=100)),
                ("customer_address_1_ship", models.CharField(max_length=100)),
                (
                    "customer_address_2_ship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("customer_town_ship", models.CharField(max_length=100)),
                ("customer_postcode_ship", models.CharField(max_length=20)),
                ("customer_county_ship", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
