# Generated by Django 4.2.19 on 2025-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="total",
            field=models.FloatField(),
        ),
    ]
