# Generated by Django 4.2.19 on 2025-03-12 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0003_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
