# Generated by Django 4.2.19 on 2025-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0004_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_status",
            field=models.CharField(
                choices=[("open", "Open"), ("paid", "Paid")],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice"),
                    ("quote", "Quote"),
                    ("receipt", "Receipt"),
                ],
                default="invoice",
                max_length=10,
            ),
        ),
    ]
