# Generated by Django 4.2.19 on 2025-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0005_invoice_invoice_status_invoice_invoice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("invoice", "Invoice"), ("receipt", "Receipt")],
                default="invoice",
                max_length=10,
            ),
        ),
    ]
