# Generated by Django 4.2.19 on 2025-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0006_alter_invoice_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="total_qty",
            field=models.IntegerField(default=0),
        ),
    ]
